[package]
name = "syslog-rx"
version = "0.2.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
edition = "2021"

[dependencies]
fmt-extra = "0.2.1"
glommio = "*"
futures-lite = "*"
listenfd = "*"

#[patch.crates-io]
#glommio = { path = "../../d/glommio/glommio" }

[profile.release]
debug = 1
